version: 2
updates:
  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: weekly
    groups:
      frontend-patches:
        update-types:
          - patch
      frontend-minors:
        update-types:
          - minor

  - package-ecosystem: pip
    directory: /apps/api
    schedule:
      interval: weekly
    groups:
      backend-patches:
        update-types:
          - patch
      backend-minors:
        update-types:
          - minor

  - package-ecosystem: docker
    directory: /apps/api
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /apps/web
    schedule:
      interval: weekly

  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
