"""Provider-neutral contracts and external feed adapters."""

from app.providers.alpaca import AlpacaMarketDataProvider, AlpacaNewsProvider
from app.providers.alpaca_broker import (
    ALPACA_LIVE_TRADING_BASE_URL,
    ALPACA_PAPER_TRADING_BASE_URL,
    AlpacaBrokerProvider,
)
from app.providers.broker import (
    BrokerAccount,
    BrokerAuthenticationError,
    BrokerCancellation,
    BrokerClock,
    BrokerConfigurationError,
    BrokerNotFoundError,
    BrokerOrder,
    BrokerOrderList,
    BrokerOrderRejectedError,
    BrokerOrderRequest,
    BrokerPayloadError,
    BrokerPosition,
    BrokerPositionList,
    BrokerProvider,
    BrokerProviderError,
    BrokerRequestError,
    BrokerTransportError,
)
from app.providers.contracts import (
    CompanyTicker,
    FilingProvider,
    FilingProviderCapabilities,
    FilingSubmission,
    FilingSubmissions,
    MarketBar,
    MarketDataCapabilities,
    MarketDataProvider,
    MarketQuote,
    MarketSnapshot,
    MarketSnapshotBatch,
    MarketTrade,
    NewsArticle,
    NewsPage,
    NewsProvider,
    NewsProviderCapabilities,
    ProviderPayloadError,
    Provenance,
    TickerMap,
)
from app.providers.sec_edgar import SecEdgarProvider, validate_sec_user_agent

__all__ = [
    "ALPACA_LIVE_TRADING_BASE_URL",
    "ALPACA_PAPER_TRADING_BASE_URL",
    "AlpacaBrokerProvider",
    "AlpacaMarketDataProvider",
    "AlpacaNewsProvider",
    "BrokerAccount",
    "BrokerAuthenticationError",
    "BrokerCancellation",
    "BrokerClock",
    "BrokerConfigurationError",
    "BrokerNotFoundError",
    "BrokerOrder",
    "BrokerOrderList",
    "BrokerOrderRejectedError",
    "BrokerOrderRequest",
    "BrokerPayloadError",
    "BrokerPosition",
    "BrokerPositionList",
    "BrokerProvider",
    "BrokerProviderError",
    "BrokerRequestError",
    "BrokerTransportError",
    "CompanyTicker",
    "FilingProvider",
    "FilingProviderCapabilities",
    "FilingSubmission",
    "FilingSubmissions",
    "MarketBar",
    "MarketDataCapabilities",
    "MarketDataProvider",
    "MarketQuote",
    "MarketSnapshot",
    "MarketSnapshotBatch",
    "MarketTrade",
    "NewsArticle",
    "NewsPage",
    "NewsProvider",
    "NewsProviderCapabilities",
    "ProviderPayloadError",
    "Provenance",
    "SecEdgarProvider",
    "TickerMap",
    "validate_sec_user_agent",
]
