"""baseline schema and phase 0 controls

Revision ID: 3a7a2c3f0c0c
Revises:
Create Date: 2026-07-29 23:59:56.755514
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3a7a2c3f0c0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


LEGACY_TABLES = {
    "automation_audit_logs",
    "automation_settings",
    "broker_order_events",
    "broker_stream_states",
    "broker_trade_updates",
    "catalysts",
    "execution_intents",
    "external_news_events",
    "integration_sync_runs",
    "journal_entries",
    "market_data_snapshots",
    "risk_settings",
    "scanner_symbols",
    "trade_plans",
    "watchlist_items",
}


def _create_provider_capability_checks() -> None:
    op.create_table('provider_capability_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('capability', sa.String(length=80), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('source_feed', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=120), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('tested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_capability_checks_capability'), 'provider_capability_checks', ['capability'], unique=False)
    op.create_index(op.f('ix_provider_capability_checks_provider'), 'provider_capability_checks', ['provider'], unique=False)
    op.create_index(op.f('ix_provider_capability_checks_status'), 'provider_capability_checks', ['status'], unique=False)
    op.create_index(op.f('ix_provider_capability_checks_tested_at'), 'provider_capability_checks', ['tested_at'], unique=False)


def _adopt_legacy_schema(existing_tables: set[str]) -> None:
    missing = LEGACY_TABLES - existing_tables
    if missing:
        raise RuntimeError(
            "Cannot adopt the legacy database because expected tables are missing: "
            + ", ".join(sorted(missing))
        )
    inspector = sa.inspect(op.get_bind())
    scanner_columns = {column["name"] for column in inspector.get_columns("scanner_symbols")}
    if "data_origin" not in scanner_columns:
        op.add_column(
            "scanner_symbols",
            sa.Column(
                "data_origin",
                sa.String(length=30),
                nullable=False,
                server_default=sa.text("'manual'"),
            ),
        )
        op.create_index(
            op.f("ix_scanner_symbols_data_origin"),
            "scanner_symbols",
            ["data_origin"],
            unique=False,
        )
    if "provider_capability_checks" not in existing_tables:
        _create_provider_capability_checks()


def upgrade() -> None:
    existing_tables = set(sa.inspect(op.get_bind()).get_table_names())
    if "scanner_symbols" in existing_tables:
        _adopt_legacy_schema(existing_tables)
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_audit_logs_action'), 'automation_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_automation_audit_logs_created_at'), 'automation_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_automation_audit_logs_outcome'), 'automation_audit_logs', ['outcome'], unique=False)
    op.create_table('automation_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_submit_approved', sa.Boolean(), nullable=False),
    sa.Column('kill_switch_engaged', sa.Boolean(), nullable=False),
    sa.Column('require_manual_approval', sa.Boolean(), nullable=False),
    sa.Column('paper_only', sa.Boolean(), nullable=False),
    sa.Column('max_orders_per_day', sa.Integer(), nullable=False),
    sa.Column('max_order_notional', sa.Float(), nullable=False),
    sa.Column('max_quote_age_seconds', sa.Integer(), nullable=False),
    sa.Column('max_price_deviation_pct', sa.Float(), nullable=False),
    sa.Column('allowed_order_types', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('broker_stream_states',
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('environment', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('last_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_disconnected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_backfill_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('reconnect_count', sa.Integer(), nullable=False),
    sa.Column('events_received', sa.Integer(), nullable=False),
    sa.Column('events_processed', sa.Integer(), nullable=False),
    sa.Column('duplicate_events', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('provider')
    )
    op.create_index(op.f('ix_broker_stream_states_status'), 'broker_stream_states', ['status'], unique=False)
    op.create_table('catalysts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('published_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('catalyst_type', sa.String(length=80), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalysts_id'), 'catalysts', ['id'], unique=False)
    op.create_index(op.f('ix_catalysts_ticker'), 'catalysts', ['ticker'], unique=False)
    op.create_table('integration_sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('requested_symbols', sa.JSON(), nullable=False),
    sa.Column('records_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('request_metadata', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_sync_runs_kind'), 'integration_sync_runs', ['kind'], unique=False)
    op.create_index(op.f('ix_integration_sync_runs_provider'), 'integration_sync_runs', ['provider'], unique=False)
    op.create_index(op.f('ix_integration_sync_runs_status'), 'integration_sync_runs', ['status'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('setup', sa.String(length=120), nullable=False),
    sa.Column('catalyst_type', sa.String(length=80), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('r_multiple', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('mistake_tags', sa.JSON(), nullable=False),
    sa.Column('followed_plan', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', ['id'], unique=False)
    op.create_index(op.f('ix_journal_entries_ticker'), 'journal_entries', ['ticker'], unique=False)
    op.create_index(op.f('ix_journal_entries_trade_date'), 'journal_entries', ['trade_date'], unique=False)
    op.create_table('market_data_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('source_feed', sa.String(length=40), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('bid', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ask', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('spread_pct', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('vwap', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('previous_close', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('delay_seconds', sa.Integer(), nullable=True),
    sa.Column('is_consolidated', sa.Boolean(), nullable=False),
    sa.Column('request_id', sa.String(length=120), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_data_snapshots_event_time'), 'market_data_snapshots', ['event_time'], unique=False)
    op.create_index(op.f('ix_market_data_snapshots_observed_at'), 'market_data_snapshots', ['observed_at'], unique=False)
    op.create_index(op.f('ix_market_data_snapshots_provider'), 'market_data_snapshots', ['provider'], unique=False)
    op.create_index(op.f('ix_market_data_snapshots_ticker'), 'market_data_snapshots', ['ticker'], unique=False)
    _create_provider_capability_checks()
    op.create_table('risk_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_size', sa.Float(), nullable=False),
    sa.Column('max_risk_per_trade_pct', sa.Float(), nullable=False),
    sa.Column('max_daily_loss', sa.Float(), nullable=False),
    sa.Column('max_trades_per_day', sa.Integer(), nullable=False),
    sa.Column('max_consecutive_losses', sa.Integer(), nullable=False),
    sa.Column('allowed_start_time', sa.Time(), nullable=False),
    sa.Column('allowed_end_time', sa.Time(), nullable=False),
    sa.Column('min_score_to_plan', sa.Integer(), nullable=False),
    sa.Column('max_spread_pct', sa.Float(), nullable=False),
    sa.Column('max_position_shares', sa.Integer(), nullable=False),
    sa.Column('require_above_vwap', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scanner_symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('gap_pct', sa.Float(), nullable=False),
    sa.Column('rel_volume', sa.Float(), nullable=False),
    sa.Column('float_m', sa.Float(), nullable=False),
    sa.Column('market_cap_m', sa.Float(), nullable=False),
    sa.Column('spread_pct', sa.Float(), nullable=False),
    sa.Column('catalyst_type', sa.String(length=80), nullable=True),
    sa.Column('above_vwap', sa.Boolean(), nullable=False),
    sa.Column('news_headline', sa.Text(), nullable=True),
    sa.Column('clean_daily_chart_room', sa.Boolean(), nullable=False),
    sa.Column('holding_key_level', sa.Boolean(), nullable=False),
    sa.Column('no_dilution_red_flag', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_origin', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scanner_symbols_data_origin'), 'scanner_symbols', ['data_origin'], unique=False)
    op.create_index(op.f('ix_scanner_symbols_id'), 'scanner_symbols', ['id'], unique=False)
    op.create_index(op.f('ix_scanner_symbols_ticker'), 'scanner_symbols', ['ticker'], unique=True)
    op.create_table('trade_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('account_size', sa.Float(), nullable=False),
    sa.Column('max_risk_per_trade_pct', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_price', sa.Float(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('risk_per_share', sa.Float(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('max_loss', sa.Float(), nullable=False),
    sa.Column('r_multiple', sa.Float(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_plans_id'), 'trade_plans', ['id'], unique=False)
    op.create_index(op.f('ix_trade_plans_plan_date'), 'trade_plans', ['plan_date'], unique=False)
    op.create_index(op.f('ix_trade_plans_ticker'), 'trade_plans', ['ticker'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_items_id'), 'watchlist_items', ['id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_ticker'), 'watchlist_items', ['ticker'], unique=True)
    op.create_table('execution_intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_plan_id', sa.Integer(), nullable=False),
    sa.Column('broker_provider', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('order_type', sa.String(length=30), nullable=False),
    sa.Column('time_in_force', sa.String(length=12), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('stop_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('client_order_id', sa.String(length=128), nullable=False),
    sa.Column('broker_order_id', sa.String(length=128), nullable=True),
    sa.Column('approval_note', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('risk_snapshot', sa.JSON(), nullable=False),
    sa.Column('quote_snapshot', sa.JSON(), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('broker_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trade_plan_id'], ['trade_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_intents_broker_order_id'), 'execution_intents', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_execution_intents_client_order_id'), 'execution_intents', ['client_order_id'], unique=True)
    op.create_index(op.f('ix_execution_intents_status'), 'execution_intents', ['status'], unique=False)
    op.create_index(op.f('ix_execution_intents_trade_plan_id'), 'execution_intents', ['trade_plan_id'], unique=True)
    op.create_table('external_news_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('source', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_external', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('promoted_catalyst_id', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['promoted_catalyst_id'], ['catalysts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', 'ticker', name='uq_external_news_event')
    )
    op.create_index(op.f('ix_external_news_events_provider'), 'external_news_events', ['provider'], unique=False)
    op.create_index(op.f('ix_external_news_events_published_at'), 'external_news_events', ['published_at'], unique=False)
    op.create_index(op.f('ix_external_news_events_ticker'), 'external_news_events', ['ticker'], unique=False)
    op.create_table('broker_order_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_intent_id', sa.Integer(), nullable=False),
    sa.Column('provider_event_id', sa.String(length=160), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=60), nullable=False),
    sa.Column('filled_qty', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('filled_avg_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['execution_intent_id'], ['execution_intents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_event_id')
    )
    op.create_index(op.f('ix_broker_order_events_execution_intent_id'), 'broker_order_events', ['execution_intent_id'], unique=False)
    op.create_index(op.f('ix_broker_order_events_occurred_at'), 'broker_order_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_broker_order_events_status'), 'broker_order_events', ['status'], unique=False)
    op.create_table('broker_trade_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_event_id', sa.String(length=200), nullable=False),
    sa.Column('stream', sa.String(length=60), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('broker_order_id', sa.String(length=128), nullable=False),
    sa.Column('client_order_id', sa.String(length=128), nullable=False),
    sa.Column('execution_intent_id', sa.Integer(), nullable=True),
    sa.Column('execution_id', sa.String(length=160), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('position_quantity', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('normalized_order', sa.JSON(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['execution_intent_id'], ['execution_intents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_broker_trade_update_event')
    )
    op.create_index(op.f('ix_broker_trade_updates_broker_order_id'), 'broker_trade_updates', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_broker_trade_updates_client_order_id'), 'broker_trade_updates', ['client_order_id'], unique=False)
    op.create_index(op.f('ix_broker_trade_updates_event_type'), 'broker_trade_updates', ['event_type'], unique=False)
    op.create_index(op.f('ix_broker_trade_updates_execution_id'), 'broker_trade_updates', ['execution_id'], unique=False)
    op.create_index(op.f('ix_broker_trade_updates_execution_intent_id'), 'broker_trade_updates', ['execution_intent_id'], unique=False)
    op.create_index(op.f('ix_broker_trade_updates_occurred_at'), 'broker_trade_updates', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_broker_trade_updates_provider'), 'broker_trade_updates', ['provider'], unique=False)
    op.create_index(op.f('ix_broker_trade_updates_received_at'), 'broker_trade_updates', ['received_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_broker_trade_updates_received_at'), table_name='broker_trade_updates')
    op.drop_index(op.f('ix_broker_trade_updates_provider'), table_name='broker_trade_updates')
    op.drop_index(op.f('ix_broker_trade_updates_occurred_at'), table_name='broker_trade_updates')
    op.drop_index(op.f('ix_broker_trade_updates_execution_intent_id'), table_name='broker_trade_updates')
    op.drop_index(op.f('ix_broker_trade_updates_execution_id'), table_name='broker_trade_updates')
    op.drop_index(op.f('ix_broker_trade_updates_event_type'), table_name='broker_trade_updates')
    op.drop_index(op.f('ix_broker_trade_updates_client_order_id'), table_name='broker_trade_updates')
    op.drop_index(op.f('ix_broker_trade_updates_broker_order_id'), table_name='broker_trade_updates')
    op.drop_table('broker_trade_updates')
    op.drop_index(op.f('ix_broker_order_events_status'), table_name='broker_order_events')
    op.drop_index(op.f('ix_broker_order_events_occurred_at'), table_name='broker_order_events')
    op.drop_index(op.f('ix_broker_order_events_execution_intent_id'), table_name='broker_order_events')
    op.drop_table('broker_order_events')
    op.drop_index(op.f('ix_external_news_events_ticker'), table_name='external_news_events')
    op.drop_index(op.f('ix_external_news_events_published_at'), table_name='external_news_events')
    op.drop_index(op.f('ix_external_news_events_provider'), table_name='external_news_events')
    op.drop_table('external_news_events')
    op.drop_index(op.f('ix_execution_intents_trade_plan_id'), table_name='execution_intents')
    op.drop_index(op.f('ix_execution_intents_status'), table_name='execution_intents')
    op.drop_index(op.f('ix_execution_intents_client_order_id'), table_name='execution_intents')
    op.drop_index(op.f('ix_execution_intents_broker_order_id'), table_name='execution_intents')
    op.drop_table('execution_intents')
    op.drop_index(op.f('ix_watchlist_items_ticker'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_trade_plans_ticker'), table_name='trade_plans')
    op.drop_index(op.f('ix_trade_plans_plan_date'), table_name='trade_plans')
    op.drop_index(op.f('ix_trade_plans_id'), table_name='trade_plans')
    op.drop_table('trade_plans')
    op.drop_index(op.f('ix_scanner_symbols_ticker'), table_name='scanner_symbols')
    op.drop_index(op.f('ix_scanner_symbols_id'), table_name='scanner_symbols')
    op.drop_index(op.f('ix_scanner_symbols_data_origin'), table_name='scanner_symbols')
    op.drop_table('scanner_symbols')
    op.drop_table('risk_settings')
    op.drop_index(op.f('ix_provider_capability_checks_tested_at'), table_name='provider_capability_checks')
    op.drop_index(op.f('ix_provider_capability_checks_status'), table_name='provider_capability_checks')
    op.drop_index(op.f('ix_provider_capability_checks_provider'), table_name='provider_capability_checks')
    op.drop_index(op.f('ix_provider_capability_checks_capability'), table_name='provider_capability_checks')
    op.drop_table('provider_capability_checks')
    op.drop_index(op.f('ix_market_data_snapshots_ticker'), table_name='market_data_snapshots')
    op.drop_index(op.f('ix_market_data_snapshots_provider'), table_name='market_data_snapshots')
    op.drop_index(op.f('ix_market_data_snapshots_observed_at'), table_name='market_data_snapshots')
    op.drop_index(op.f('ix_market_data_snapshots_event_time'), table_name='market_data_snapshots')
    op.drop_table('market_data_snapshots')
    op.drop_index(op.f('ix_journal_entries_trade_date'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_ticker'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_integration_sync_runs_status'), table_name='integration_sync_runs')
    op.drop_index(op.f('ix_integration_sync_runs_provider'), table_name='integration_sync_runs')
    op.drop_index(op.f('ix_integration_sync_runs_kind'), table_name='integration_sync_runs')
    op.drop_table('integration_sync_runs')
    op.drop_index(op.f('ix_catalysts_ticker'), table_name='catalysts')
    op.drop_index(op.f('ix_catalysts_id'), table_name='catalysts')
    op.drop_table('catalysts')
    op.drop_index(op.f('ix_broker_stream_states_status'), table_name='broker_stream_states')
    op.drop_table('broker_stream_states')
    op.drop_table('automation_settings')
    op.drop_index(op.f('ix_automation_audit_logs_outcome'), table_name='automation_audit_logs')
    op.drop_index(op.f('ix_automation_audit_logs_created_at'), table_name='automation_audit_logs')
    op.drop_index(op.f('ix_automation_audit_logs_action'), table_name='automation_audit_logs')
    op.drop_table('automation_audit_logs')
    # ### end Alembic commands ###
